name: dscim-epa
channels:
  - conda-forge
  - defaults
dependencies:
  - google-cloud-storage==2.5.0
  - statsmodels==0.13.2
  - python==3.9
  - pyfiglet==0.8.post1
  - pip==22.2.2
  - xarray==2022.3.0
  - pandas==1.4.3
  - numpy==1.23.3
  - scipy==1.9.1
  - jupyterlab==3.4.7
  - ipython==8.5.0
  - matplotlib==3.5.3
  - dask==2022.9.0
  - pytest==7.1.3
  - pytest-cov==3.0.0
  - papermill==2.3.4
  - click==8.1.3
  - netcdf4==1.6.0
  - h5netcdf==1.0.2
  - zarr==2.12.0
  - cftime==1.6.1
  - bottleneck==1.3.5
  - nc-time-axis==1.4.1
  - jupyterlab_widgets==3.0.3
  - pip:
      - dscim==0.3.0
      - black==22.1.0
      - flake8==5.0.4
      - dill==0.3.5.1
      - numbagg==0.2.1
      - p_tqdm==1.4.0
      - impactlab_tools==0.4.0
      - inquirer==2.10.0
