global-options:
    nsamps: 10000
    scenario: ssp245
    pyear_start: 2020
    pyear_end: 2300
    pyear_step: 1
    baseyear: 2005
    pipeline_file: 'pipeline.global.yml'


climate_step:
    dummy:
        module_set: "facts"
        module: "dummy"
        pipeline_file: 'pipeline.yml'
        input_data_file:
            - "ohc.nc4"
            - "gsat.nc4"
            - "climate.nc4"
        climate_output_data:
            - "ohc.nc4"
            - "gsat.nc4"
            - "climate.nc4"
        generates_climate_output: true

sealevel_step:
    GrIS1f:
        module_set: "FittedISMIP"
        module: "GrIS"
        options:
            crateyear_start: 2080
            crateyear_end: 2100
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"
            - "wf2f"

    larmip:
        module_set: "larmip"
        module: "AIS"
        options_allowoverwrite:
           climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf2f"

    ar5glaciers:
        module_set: "ipccar5"
        module: "glaciers"
        options:
            gmip: 2
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"
            - "wf2f"

    ar5AIS:
        module_set: "ipccar5"
        module: "icesheets"
        pipeline_file: "pipeline.AIS.global.yml"
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"

    ocean:
        module_set: "tlm"
        module: "sterodynamics"
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"
            - "wf2f"

    lws:
        module_set: "ssp"
        module: "landwaterstorage"
        options:
            scenario: "ssp5"
            dcrate_lo: -0.4
        include_in_workflow:
            - "wf1f"
            - "wf2f"

totaling_step:
    total:
        module_set: "facts"
        module: "total"
        loop_over_workflows: true
        loop_over_scales: true
        stages:
            - workflow
